version: "2"

services:
    plex:
        image: linuxserver/plex
        container_name: plex
        environment:
            - VERSION="latest"
            - PUID="1000"
            - PGID="1000"
            - TZ="Europe/London"
        volumes:
            - ./../config:/config
            - ./../tvshows:/data/tvshows
            - ./../movies:/data/movies
            - ./../music:/data/music
            - ./../transcode:/transcode
        network_mode: "host"

        
