version: "3"

services:
    plex:
        image: linuxserver/plex
        container_name: plex
        environment:
            - VERSION="latest"
            - PUID=1000
            - PGID=1000
            - TZ="Europe/London"
        volumes:
            - ./../config:/config
            - ./../data:/data
        network_mode: "host"

        
